url: http://ruidechua.github.io
baseurl: /portfolio/

# Site settings
title: RD's Portfolio
email: hello@rdchua.com
description: "Portfolio of Chua Rui De."


# Team names, titles and social links
people:
- name: Chua
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Rui 
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Dee
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/rdchua/
  - title: facebook
    url: https://www.facebook.com/ruidechua
  - title: github
    url: http://github.com/ruidechua
  - title: flickr
    url: http://stackoverflow.com/questions/tagged/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
